### ISSUE TITLE
[bug] "Cannot read property 'loc' of undefined"

### ISSUE THREAD

**Issue by SpainTrain** [wix/eslint-plugin-lodash#113]
`preferred-alias` rule is throwing a fatal error rather than reporting the rule violation.

LMK if any more information is helpful.

Full error output:

```
Cannot read property 'loc' of undefined
TypeError: Cannot read property 'loc' of undefined
    at RuleContext.report (/home/spainhower/repos/hz-webapp/node_modules/eslint/lib/rule-context.js:129:50)
    at /home/spainhower/repos/hz-webapp/node_modules/eslint-plugin-lodash/lib/rules/preferred-alias.js:35:25
    at EventEmitter.<anonymous> (/home/spainhower/repos/hz-webapp/node_modules/eslint-plugin-lodash/lib/util/lodashUtil.js:97:17)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/home/spainhower/repos/hz-webapp/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/home/spainhower/repos/hz-webapp/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/home/spainhower/repos/hz-webapp/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (/home/spainhower/repos/hz-webapp/node_modules/eslint/lib/eslint.js:898:36)
    at Controller.__execute (/home/spainhower/repos/hz-webapp/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
```

source file:

```js
import {first} from 'lodash'

first()
```

.eslintrc.yaml

```yaml
---
parser: babel-eslint
parserOptions:
    ecmaVersion: 6
    ecmaFeatures:
        impliedStrict: true
        jsx: true
        experimentalObjectRestSpread: true
    sourceType: module
env:
    es6: true
    node: true
plugins:
    - lodash
    - lodash-fp
    - react
extends:
    - plugin:react/recommended
    - plugin:lodash/recommended
rules:
    lodash/path-style:
        - 2
        - as-needed
    lodash/prefer-lodash-method: 2
    lodash-fp/no-chain: 2
    lodash-fp/no-argumentless-calls: 2
    lodash-fp/no-extraneous-iteratee-args: 2
    lodash-fp/no-single-composition: 2
    lodash-fp/no-submodule-destructuring: 2
    lodash-fp/prefer-flat-map: 2
    jsx-quotes:
        - 2
        - prefer-single
    no-var: 2
    prefer-const: 2
    prefer-spread: 2
    react/display-name:
        - 2
        -   ignoreTranspilerName: false
    react/jsx-closing-bracket-location:
        - 2
        -   selfClosing: after-props
            nonEmpty: tag-aligned
    react/jsx-curly-spacing: 2
    react/jsx-indent: 2
    react/jsx-indent-props: 2
    react/jsx-key: 2
    react/jsx-uses-vars: 2
    react/jsx-uses-react: 2
    react/jsx-no-bind: 2
    react/jsx-no-duplicate-props: 2
    react/jsx-no-literals: 2
    react/jsx-no-undef: 2
    react/jsx-pascal-case: 2
    react/jsx-wrap-multilines: 2
    react/no-danger: 2
    react/no-deprecated: 2
    react/no-did-mount-set-state: 2
    react/no-did-update-set-state: 2
    react/no-direct-mutation-state: 2
    react/no-is-mounted: 2
    react/no-multi-comp: 0 # proposed
    react/no-set-state: 2
    react/no-unknown-property: 2
    react/prop-types: 2
    react/self-closing-comp: 2
    react/sort-comp: 2
    react/sort-prop-types:
        - 2
        -   callbacksLast: true
            requiredFirst: true
    strict:
        - 2
        - never
...
```

versions:

```bash
$ npm ls | grep eslint
├─┬ babel-eslint@7.0.0
├─┬ eslint@3.8.0
├── eslint-plugin-lodash@2.1.4
├─┬ eslint-plugin-lodash-fp@2.1.1
│ ├── create-eslint-index@1.0.0
├─┬ eslint-plugin-react@6.4.1
```

```bash
$ npm ls | grep babel
├─┬ babel-cli@6.16.0
│ ├─┬ babel-register@6.16.3
├─┬ babel-core@6.17.0
[truncated. available if needed]
```
